name: LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: 《微分几何入门与广义相对论》附录G“李群和李代数”习题解答
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: 《微分幾何入門與廣義相對論》附錄G“李群和李代數”習題解答.tex
          working_directory: 《微分几何入门与广义相对论》附录G“李群和李代数”习题解答
      - name: 光学
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: main.tex
          working_directory: 光学
      - name: 固体物理
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: main.tex
          working_directory: 固体物理
      - name: 戒为良药
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: main.tex
          working_directory: 戒为良药
      - name: 数学物理方法
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: main.tex
          working_directory: 数学物理方法
      - name: 热力学与统计物理学
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: main.tex
          working_directory: 热力学与统计物理学
      - name: 电动力学
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: main.tex
          working_directory: 电动力学
      # - name: 电磁学
      #   uses: xu-cheng/latex-action@v3
      #   with:
      #     latexmk_shell_escape: true
      #     latexmk_use_lualatex: true
      #     root_file: main.tex
      #     working_directory: 电磁学
      - name: 黄帝内经
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: main.tex
          working_directory: 黄帝内经
      - name: others
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: |
            Comments_in_'Supersymmetric_Quantum_Mechanics_by_David_Tong'.tex
            temp.tex
            小狗钱钱2.tex
            微积分.tex
            量子场论_by_David_Tong.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: notes_ph3n92h3
          path: |
            《微分几何入门与广义相对论》附录G“李群和李代数”习题解答/《微分幾何入門與廣義相對論》附錄G“李群和李代數”習題解答.pdf
            光学/main.pdf
            固体物理/main.pdf
            戒为良药/main.pdf
            数学物理方法/main.pdf
            热力学与统计物理学/main.pdf
            电动力学/main.pdf
            # 电磁学/main.pdf
            黄帝内经/main.pdf
            Comments_in_'Supersymmetric_Quantum_Mechanics_by_David_Tong'.pdf
            temp.pdf
            宇宙学微扰理论 by Hannu Kurki-Suonio.pdf
            小狗钱钱2.pdf
            微积分.pdf
            群论和表示论 by Andre Lukas and Hannah Tillim.pdf
            量子场论_by_David_Tong.pdf
